language: android
android:
  components:
  - build-tools-26.0.2
  - android-26
deploy:
  provider: releases
  api_key:
    secure: hXtmU4Kq/AWTqan6aMpkElTVNdXHfZHws4rIVYq2Epc7SD73zicC2lSDMRCx/02ku5b/gm2b/rvOC6oEawL3V6ykMmWIHsikeaPp2VlIgGzie3XpRDvMZ2utHzjMh/rCAoIeF8LuHQb+hBjB58KM+aaFpServK5eJZSLOphiTi+8gFHQIF7HSrFhhOdyXnu4G/f2kSLl3RYRQU3t+16AYYPqmKPjiqEd+FzggxM5iEUdDzdUeBnvfuabt3L0IjK9sW8uABBiAXiFcuGCTx/8Rjoi/gU2m1PBW8YVu9l53DD3EMhWtgcH3xZDyzZGWdh8wLGemcyaf6WxaBLaW4mR4V6xylXcakCiBOcPhAkdVjtKvG2XlW5P00LomzhVOdfmBmy5eE453n3iZlSQKfbJzA6fMwPRmQfK/QgpsyRMaSGVb9/i0bvVVu3TiKcg+KydBvEh2PF4j1zasiy1zrCgki23Fosw8+9Y27fg854rvQ9SeK9zsiqnC1KgBY7Fd6zKdxXjtz2JkPw0yDSlIbgIjGHep7Xn/s6XDYVH8+q9AsmJfxn/dgI+ReTfmRis59+dzThqAY4BFGSuaO0KCdn6aB9NfxXGxE0UQNvuLsRosmKQWgjcJgEKTwujqD46gchS2O6HfjxF4N9P/LAuyxC8WovGd+fnKJ8guYxQHqsRqzg=
  file: app/build/outputs/apk/release/app-release-unsigned.apk
  on:
    repo: stevesoltys/backup
    tags: true
  skip_cleanup: true